### ISSUE TITLE
Get set user karma level for admin

### ISSUE THREAD

**Issue by jghibiki** [jghibiki/mopey#31]

**Comment by jghibiki** [comment]
Not sure how 0dc5621 closes this issue...

**Comment by JPisaBrony** [comment]
the only thing that needed to change was for it to require admin since the edit user already covers changing the karma, but im guessing you wanted an explicit call to is as with the get methods

**Comment by jghibiki** [comment]
Yeah. The reason for explicit calls is that the response time is shorter due to the smalled response packet size.

**Comment by JPisaBrony** [comment]
2a9010f
should fix this

**Comment by jghibiki** [comment]
Do #fixes <issue number> in you commit message to auto close.

**Comment by jghibiki** [comment]
#fixes issue number

**Comment by JPisaBrony** [comment]
I just wanted to make sure you saw it before closing/reopening it again
