### ISSUE TITLE
UI UX Working idea

### ISSUE THREAD

**Issue by jghibiki** [jghibiki/mopey#36]

**Comment by JPisaBrony** [comment]
![img_20150430_141515](https://cloud.githubusercontent.com/assets/3083689/7420647/c4b10b56-ef43-11e4-83d4-7c1f355b3d27.jpg)

**Comment by jghibiki** [comment]
:rotating_light:

**Comment by JPisaBrony** [comment]
![14304215796581562402710](https://cloud.githubusercontent.com/assets/3083689/7420672/fe65033e-ef43-11e4-8ebc-b42ff765137d.jpg)

**Comment by jghibiki** [comment]
The base of this idea is implemented so i'm closing the issue.
