### ISSUE TITLE
Change edit use usage

### ISSUE THREAD

**Issue by jghibiki** [jghibiki/mopey#52]
Edit user api should be changed to:

```
POST /user/<user id>/edit
```

**Comment by JPisaBrony** [comment]
how exactly do you want that to work though? where is the data going to be comming from? with the current code, you do a POST /user/edit username=jdoe password=boi firstName=john lastName=doe email=jdoe@gmail.com karma=0 strikes=0

**Comment by jghibiki** [comment]
Yeah the data would still come over in the json payload, you'd just get the user key from the uri.
