### ISSUE TITLE
Change ban user route

### ISSUE THREAD

**Issue by jghibiki** [jghibiki/mopey#53]
Change ban user route to 

```
GET /users/<user id>/ban

```

Could add

```

GET /users/<user id>/banned
```

To to check to see if user is banned, response would be {"result": <bool>}

**Comment by jghibiki** [comment]
Change un an while at it

**Comment by jghibiki** [comment]
*unban

**Comment by JPisaBrony** [comment]
so are you saying instead of 2 methods, combind it into one?

**Comment by JPisaBrony** [comment]
2a9010f
should fix it. it returns the strikes but if you want it to return nothing, I can change it to that

**Comment by jghibiki** [comment]
This commit has nothing to do with the issue... the issue is about banning that commit is about karma.

**Comment by JPisaBrony** [comment]
oops i ment
c9f09251aa7c20f7c1c83d11c6f29ea4326e8b49

**Comment by jghibiki** [comment]
Looks good :+1:
